---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Pets"
  license:
    name: "MIT"
host: "127.0.0.1:8080"
basePath: "/v2"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /pets:
    get:
      tags:
      - "pet"
      summary: "Get all pets"
      description: ""
      operationId: "get_all_pets"
      parameters: []
      responses:
        "200":
          description: "List of pets"
        default:
          description: "Unexpected error"
      x-swagger-router-controller: "swagger_server.controllers.pet_controller"
    post:
      tags:
      - "pet"
      summary: "Add a new pet"
      description: ""
      operationId: "add_pet"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Pet"
      responses:
        "200":
          description: "Pet added"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.pet_controller"
  /pets/{petId}:
    get:
      tags:
      - "pet"
      summary: "Find pet by ID"
      description: "Returns a single pet"
      operationId: "get_pet_by_id"
      parameters:
      - name: "petId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Pet"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      x-swagger-router-controller: "swagger_server.controllers.pet_controller"
definitions:
  Pet:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "doggie"
      age:
        type: "integer"
        format: "int64"
    xml:
      name: "Pet"
    example:
      name: "doggie"
      id: 0
      age: 6
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
